---
name: learn-bosh

releases:
- name: learn-bosh
  version: latest

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

instance_groups:
- name: app
  instances: 1
  vm_type: small
  stemcell: default
  azs: [vsphere]
  networks:
  - name: vsphere-default
  jobs:
  - name: app
    release: learn-bosh

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 10